version: "4.2"
services:
  spring_boot_user_auth_service:
    container_name: spring_boot_user_auth_service
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      springboot-mysql-net:
    environment:
      - spring.datasource.url=jdbc:mysql://spring-boot-mysqldb:3306/authentication?allowPublicKeyRetrieval=true
    depends_on:
      - spring-boot-mysqldb

    volumes:
      - .m2:/root/.m2

  spring-boot-mysqldb:
    container_name: spring-boot-mysqldb
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      springboot-mysql-net:
    environment:
      MYSQL_DATABASE: authentication
      MYSQL_ROOT_PASSWORD: root

networks:
  springboot-mysql-net:



